language: c
os:
  - linux
  - osx
  - windows
sudo: false
cache:
  directories:
    - node_modules
install: make
scripts:
  - make release RELEASE_OPTIONS="-version v0.0.0 -dry" | grep "v0.0.1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -patch -dry" | grep "v0.0.1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -minor -dry" | grep "v0.1.0"
  - make release RELEASE_OPTIONS="-version v0.0.1 -major -dry" | grep "v1.0.0"
  - make release RELEASE_OPTIONS="-version v0.0.1 -alpha -dry" | grep "v0.0.1-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -f -alpha -dry" | grep "v0.0.2-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -beta -dry" | grep "v0.0.1-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -f -beta -dry" | grep "v0.0.2-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -dev -dry" | grep "v0.0.1-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -f -dev -dry" | grep "v0.0.2-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1 -rc -dry" | grep "v0.0.1-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1-rc1 -rc -dry" | grep "v0.0.1-rc2"
  - make release RELEASE_OPTIONS="-version v0.0.1 -f -rc -dry" | grep "v0.0.2-rc1"
  - make release RELEASE_OPTIONS="-version v0.0.1-rc1 -clear -dry" | grep "v0.0.2"
after_script:
  - echo 'all good'
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
# addons:
#   sonarcloud:
#     organization: "templ-project"
#     token:
#       secure: r5HrVIMWtNhWKJAKViREyARl3UAHDfJreL0oLTxzY/isOvcDTHMr3xbx+nCJIIKRacVpamDm91oZv1KW16V9ZFL1h/vEobzjxyt4bPoHZHukLj+UvV4QvVJsAgZBAQsjBo75JtDPFhWAHgQOosWkx3u41RMGRNOP7QlOoO3CaJwynN5uhyOvKJ2KtjNNVjiBf0rM0x/qfrKtV9LXN8C+6tTK2/YesvR1jJYzTCYi+fgLNfSqz9pOs5AwrnEWQIBpyDwICTTgZOt55dGbQWVUhg2I8b+XjvVso5K1B8ovbNYBICVvf6EUnHne5uoa0h9FrJPbsp9g1tktnFBscQMV8Pi9wX4A/FE8SZzPR9JH3t5Udm6MeKKBwz4q1CJF20BYMnTaMUy/GZtpN2fI0Pnq34VOAwQLzWuY9idM+AYlbmES2TbDH0MDcM/R5d38fCa8Z5MrQjDAD500K/kx1zJFh00N+G+BiQDape6+MhxfpwwZpc6CGXpb5feBJn06iglv0Fjqr2ux4tzjuH5pV342S8mtya4l5GP31P5Vs/nvwdgIlb1ucNcM7oN6Gwu8yWPUgBQXxapPybUEaDpVCIpcIX3n5g/SUXVOHjCyOqJfGv2+LEdKWA+v7WsKRsJfA7F+867dBkOoDQy3CXiRWj7tZiIShzkCZaB6Om6ZIGeXJYM=
